TopCategory = ProductCategory.new(:name => 'Main')
back_on_track = TopCategory.child_product_categories.build(:id => '91', :name => 'Back on Track')
dorwest_herbs = TopCategory.child_product_categories.build(:id => '97', :name => 'Dorwest Herbs')
herkut = TopCategory.child_product_categories.build(:id => '68', :name => 'Herkut')
herkut = TopCategory.child_product_categories.build(:id => '108', :name => 'Herkut')
kala_herkut = herkut.child_product_categories.build(:id => '114', :name => 'Kala herkut')
kana_ankka_herkut = herkut.child_product_categories.build(:id => '111', :name => 'Kana / ankka herkut')
lammas_herkut = herkut.child_product_categories.build(:id => '112', :name => 'Lammas herkut')
nauta_herkut = herkut.child_product_categories.build(:id => '109', :name => 'Nauta herkut')
peura_hevonen_herkut = herkut.child_product_categories.build(:id => '113', :name => 'Peura / hevonen herkut')
possu_herkut = herkut.child_product_categories.build(:id => '110', :name => 'Possu herkut')
hoitotuotteet = TopCategory.child_product_categories.build(:id => '83', :name => 'Hoitotuotteet')
kissalle = TopCategory.child_product_categories.build(:id => '98', :name => 'Kissalle')
koiranmakkarat_ja_t_lkkiruoat = TopCategory.child_product_categories.build(:id => '100', :name => 'Koiranmakkarat ja tölkkiruoat')
kuivaruoat = TopCategory.child_product_categories.build(:id => '67', :name => 'Kuivaruoat')
bestes_futter = kuivaruoat.child_product_categories.build(:id => '87', :name => 'Bestes-Futter')
cat_emotion_kissojen_t_ysravinnot = kuivaruoat.child_product_categories.build(:id => '90', :name => 'CatEmotion kissojen täysravinnot')
golden_eagle = kuivaruoat.child_product_categories.build(:id => '121', :name => 'Golden Eagle')
josera_basic_line = kuivaruoat.child_product_categories.build(:id => '84', :name => 'Josera BasicLine')
josera_emotion_line = kuivaruoat.child_product_categories.build(:id => '85', :name => 'Josera EmotionLine')
kuivatut_lihat = kuivaruoat.child_product_categories.build(:id => '86', :name => 'Kuivatut lihat')
natural_menu = kuivaruoat.child_product_categories.build(:id => '103', :name => 'Natural Menu')
ziwi_peak = kuivaruoat.child_product_categories.build(:id => '96', :name => 'ZiwiPeak')
lahjakortti = TopCategory.child_product_categories.build(:id => '106', :name => 'Lahjakortti')
lis_ravinteet = TopCategory.child_product_categories.build(:id => '104', :name => 'Lisäravinteet')
luut = TopCategory.child_product_categories.build(:id => '65', :name => 'Luut')
broileri = luut.child_product_categories.build(:id => '76', :name => 'Broileri')
muut = luut.child_product_categories.build(:id => '77', :name => 'Muut')
nauta = luut.child_product_categories.build(:id => '75', :name => 'Nauta')
possu = luut.child_product_categories.build(:id => '74', :name => 'Possu')
pakaste_lihat = TopCategory.child_product_categories.build(:id => '3', :name => 'Pakaste lihat')
broileri = pakaste_lihat.child_product_categories.build(:id => '12', :name => 'Broileri')
kalkkuna = pakaste_lihat.child_product_categories.build(:id => '15', :name => 'Kalkkuna')
lammas = pakaste_lihat.child_product_categories.build(:id => '14', :name => 'Lammas')
lohi = pakaste_lihat.child_product_categories.build(:id => '11', :name => 'Lohi')
muut = pakaste_lihat.child_product_categories.build(:id => '89', :name => 'Muut')
nauta = pakaste_lihat.child_product_categories.build(:id => '10', :name => 'Nauta')
poro = pakaste_lihat.child_product_categories.build(:id => '88', :name => 'Poro')
possu = pakaste_lihat.child_product_categories.build(:id => '13', :name => 'Possu')
pakaste_mixit = TopCategory.child_product_categories.build(:id => '66', :name => 'Pakaste mixit')
hurja___ateriat = pakaste_mixit.child_product_categories.build(:id => '122', :name => 'HURJA - ateriat')
kavisseokset = pakaste_mixit.child_product_categories.build(:id => '82', :name => 'Kavisseokset')
kennelpakaste_mixit = pakaste_mixit.child_product_categories.build(:id => '105', :name => 'Kennelpakaste mixit')
murre_mixit = pakaste_mixit.child_product_categories.build(:id => '72', :name => 'MurreMixit')
murren_alkuvoima = pakaste_mixit.child_product_categories.build(:id => '116', :name => 'Murren Alkuvoima')
musch_suurkuluttajatuotteet = pakaste_mixit.child_product_categories.build(:id => '118', :name => 'Musch suurkuluttajatuotteet')
mush_b_a_r_f_basic_mix = pakaste_mixit.child_product_categories.build(:id => '95', :name => 'MUSH B.A.R.F Basic Mix')
mush_b_a_r_f_vaisto = pakaste_mixit.child_product_categories.build(:id => '120', :name => 'MUSH B.A.R.F Vaisto')
neut = pakaste_mixit.child_product_categories.build(:id => '73', :name => 'Neut')
puhti = pakaste_mixit.child_product_categories.build(:id => '71', :name => 'Puhti')
vom_og_hundemat = pakaste_mixit.child_product_categories.build(:id => '123', :name => 'Vom og Hundemat')
palautuminen_nesteytys = TopCategory.child_product_categories.build(:id => '119', :name => 'Palautuminen / nesteytys')
tarvikkeet = TopCategory.child_product_categories.build(:id => '70', :name => 'Tarvikkeet')
kirjat = tarvikkeet.child_product_categories.build(:id => '94', :name => 'Kirjat')
koiran_pedit_ja_peitot = tarvikkeet.child_product_categories.build(:id => '107', :name => 'Koiran pedit ja peitot')
kong_lelut = tarvikkeet.child_product_categories.build(:id => '117', :name => 'Kong lelut')
koulutustarvikkeet = tarvikkeet.child_product_categories.build(:id => '79', :name => 'Koulutustarvikkeet')
lelut = tarvikkeet.child_product_categories.build(:id => '80', :name => 'Lelut')
pannat_ja_taluttimet = tarvikkeet.child_product_categories.build(:id => '115', :name => 'Pannat ja taluttimet')
ruokailu = tarvikkeet.child_product_categories.build(:id => '78', :name => 'Ruokailu')
turvallisuus = tarvikkeet.child_product_categories.build(:id => '101', :name => 'Turvallisuus')
vetotarvikkeet = tarvikkeet.child_product_categories.build(:id => '102', :name => 'Vetotarvikkeet')
viljat = TopCategory.child_product_categories.build(:id => '99', :name => 'Viljat')
vitamiinit_ja_ljyt = TopCategory.child_product_categories.build(:id => '69', :name => 'Vitamiinit ja öljyt')
TopCategory.save
